//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amanye
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolTable
    {
        public long Id { get; set; }
        public string SchoolName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Proprietor { get; set; }
    }
}
